### ISSUE TITLE
Server side caching does not respect content negotiation

### ISSUE THREAD

**Issue by sergey-netdev** [filipw/AspNetWebApi-OutputCache#112]
An action is decorated with `[CacheOutput(ServerTimeSpan = 600]`] and caching works as advertised. However, any cache hit returns content in format requested on the first cache miss. 

Microsoft.AspNet.* is 5.2.2 targeting .NET 4.5, Strathweb.CacheOutput.WebApi2 is 0.6

**Comment by filipw** [comment]
please upgrade to latest - not able to reproduce this anymore
