### ISSUE TITLE
Global caching setting

### ISSUE THREAD

**Issue by ssvaidya** [filipw/AspNetWebApi-OutputCache#116]
I would like to know if I can set up a Global caching setting for WebApi OutputCache in the Global.asax file rather than setting up attributes on each and every individual method.  I would like to set a Global value for all caching of my methods in Web Api and then override those values when necessary on methods that require them.  I want a Global caching strategy similar to the Global registration of the Handle Error attribute in ASP.NET MVC.

Please advise as to how to accomplish this.

**Comment by cdroulers** [comment]
You can add it as a global filter just like the HandleErrorAttribute.

In FilterConfig.cs

    filters.Add(new CacheOutputAttribute() { ClientTimeSpan = 24 * 60 * 60, ServerTimeSpan = 24 * 60 * 60 });

**Comment by filipw** [comment]
that is correct, just use as a global filter

**Comment by JayCallas** [comment]
This does not seem to work -- at least when using version 1.0.0.0 of package 0.10.0.

```
public static void RegisterGlobalFilters(System.Web.Http.Filters.HttpFilterCollection filters) {
	//filters.Add(new WebApi.OutputCache.V2.CacheOutputAttribute() { NoCache = true });
	//filters.Add(new WebApi.OutputCache.V2.CacheOutputAttribute() { ClientTimeSpan = 100 });
}
```

Setting either of these has no affect on the Response Headers. Yet...

```
//[WebApi.OutputCache.V2.CacheOutput(NoCache = true)]
//[WebApi.OutputCache.V2.CacheOutput(ClientTimeSpan = 100)]
public class SearchApiController {
	...
```

does.
