### ISSUE TITLE
Response without charset

### ISSUE THREAD

**Issue by hermsdorff** [filipw/AspNetWebApi-OutputCache#117]
if I execute a query ending with a slash (http://myapp/api/test/) and the same query without the slash (http://myapp/api/test) the fist one have charset in it´s response and the second one does not have the charset.

**Comment by fredericDelaporte** [comment]
Maybe I saw the same issue as you, maybe not: your description is a bit too short to be sure what is the issue you are reporting.
Is it following issue?

It looks like output cache does alter the json content-type on cached response. When cache is not hit, the web api emit "application/json; charset=utf-8" as json response content-type.
But when the cache is hit, the charset part is dropped, the json response content-type becomes "application/json".

This should not cause issues to compliant browsers, which are supposed to understand byte order mask when present, and default to utf-8 if there is no BOM.

But I would rather have the cache to honor the original response content-type.

**Comment by filipw** [comment]
this has now been resolved, `charset=utf-8` is there by default if no charset is provided by the action
