### ISSUE TITLE
Cannot use web api liraries 5.2.3

### ISSUE THREAD

**Issue by maxlego** [filipw/AspNetWebApi-OutputCache#119]
When using web api libraries 5.2.3, i cannot install my service which hosts the api. the installer throws an exception "System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information."

I managed to detect that types were from WebApi.OutputCache.V2.
And the difference is that originally WebApi.OutputCache.V2 refers to web api libraries 5.2.2

Adding assemblyBindings did not solve the problem.
Only when i reverted to 5.2.2, i was able to install the service.

**Comment by filipw** [comment]
The latest nuget package has been upgrade to 5.2.3 - there should be no issues anymore
