### ISSUE TITLE
invalidate cache in load balanced env

### ISSUE THREAD

**Issue by krishnasingh1818** [filipw/AspNetWebApi-OutputCache#124]
if my webapi is deployed in load balanced env and say resource x is cached on both servers. now i do a  post operation which goes via server A so server A cache will get refreshed.  what about server B will it have same old cached data ? if yes then how can i invalidate cache on all loadbalanced webapi servers.

**Comment by cdroulers** [comment]
You probably need to implement your own IApiOutputCache to be distributed (using memcached or SQL Server or any other preference you may have).

**Comment by filipw** [comment]
yes there is a provider for Azure on Nuget, otherwise you create your own and store/invalidate however you need

**Comment by johnib** [comment]
> yes there is a provider for Azure on Nuget

@filipw - can you shed some light on this please?
