### ISSUE TITLE
Can I invalidate cache of an action for a particular user?

### ISSUE THREAD

**Issue by pritamkarmakar** [filipw/AspNetWebApi-OutputCache#128]
Quick question regarding cache invalidation. Lets say I have 2 actions 
````
UpdateProfile(Profile profile) and 
GetProfile(string userid)
````

I want to invalidate GetProfile for a user who will make the UpdateProfile call, but for other users it shouldn't invalidate the cache. How I can do this? Thanks in advance.

**Comment by mikkark** [comment]
I have a similar situation. In your case I think you should be able to use the normal cache.RemoveStartsWith method. In your cache you probably have keys like <controllername>-getprofile-userid=<user id here>, so you could remove the keys starting with (e.g.) "profile-getprofile-userid=13". I'm using Azure Redis as cache + my user id comes from an Oauth access token header, so I've had to create my own key generator, but the idea should be the same.

The cache invalidation instructions on webapioutputcache project site are a good read, but you've probably been there already anyway.

**Comment by pritamkarmakar** [comment]
@mikkark -- great thanks for your help. I'm able to invalidate specific cache using using RemoveStartsWith method.
