### ISSUE TITLE
Cross-Browser support

### ISSUE THREAD

**Issue by glthomas** [filipw/AspNetWebApi-OutputCache#131]
How can this Attribute be used such that the cache will be used across all browsers.  Currently the Controller Method is getting cached per browser.  It is as if the request headers are being used in the generation of the cache key.  Help on this is greatly appreciated.

**Comment by filipw** [comment]
it is not caching per browser - the caching is done per controller/action combination and a the requested media type.

If 2 browsers request the same resource, with the same media type, the response will obviously be shared between them
