### ISSUE TITLE
Can I use OutputCache with filters and paging in get of controllers? 

### ISSUE THREAD

**Issue by josunedesosa** [filipw/AspNetWebApi-OutputCache#141]
Hello,

I need to use filters and paging in get actions of controllers. 
Will I have any problems if I use OutputCache to cache this actions?

Thanks.

Josune

**Comment by pritamkarmakar** [comment]
OutputCache cahe the action along with the input action parameter. So it will work fine. I have used for same scenario.

**Comment by josunedesosa** [comment]
Thank you for answering.
Cacheoutput is a great work.
