### ISSUE TITLE
InvalidateCacheOutput not working as intended

### ISSUE THREAD

**Issue by cskiwi** [filipw/AspNetWebApi-OutputCache#164]
Hi,

I had the issue that my cache wasn't invalidated when I wanted it to be.
I went on a quest to figure out why;

The problem was in the end rather easy;

Let's say you have the following setup:
```csharp
namespace Api.Controllers {
	public class SomeController : ApiController {
		[CacheOutput(ClientTimeSpan = 0, ServerTimeSpan = 86400)]
		public IHttpActionResult GetDocument(int id) {
			// do something
		}
	}
}
```

this would add the following cache key; `api.controllers.somecontrollers.getdocument-id` and Id being replaced by the actual id

But when using a `[InvalidateCacheOutput("GetDocument", typeof(SomeController ))]`

this would remove any cachekey starting with `somecontroller-getdocument`, but the cache key that was added starts with the namespace, thus resulting with the key remaining

Unless I'm missing something, this isn't the expected result I recon?

greetings Glenn

**Comment by Jan-Olof** [comment]
Yes, this seems correct. We have the same experience.

**Comment by filipw** [comment]
Fixed in https://github.com/filipw/AspNetWebApi-OutputCache/pull/162
