### ISSUE TITLE
IModelBinder

### ISSUE THREAD

**Issue by jmucza** [filipw/AspNetWebApi-OutputCache#169]
Hi Philip,

My project has a few complex controller method arguments injected by custom IModelBinder implementations. I observed that the API output cache for those methods does not work as expected because CacheOutputAttribute.OnActionExecuting executes before IModelBinder.BindModel.

If there any way to ensure IModelBinder.BindModel always executes before CacheOutputAttribute.OnActionExecuting?

Best regards,
Janos

**Comment by jmucza** [comment]
The issue happens when only server side caching is enabled.

**Comment by filipw** [comment]
Web API doesn't allow to specify/guarantee filter order unfortunately (that's a limitation of the framework).
I have blogged about the workaround a while ago. hope it helps http://www.strathweb.com/2012/06/control-the-execution-order-of-your-filters-in-asp-net-web-api/
