### ISSUE TITLE
Encoding for cached response problem

### ISSUE THREAD

**Issue by ilant** [filipw/AspNetWebApi-OutputCache#54]
Hi, cached version of web api control response has not encoding set properly, how it can be fixed (in screenshot there is example of response, there the content-type of doesnt has the encoding attribute at all).

Thanks.

![response-cached](https://f.cloud.github.com/assets/3692867/2022842/fb7aa718-8852-11e3-8f6c-6e1ad2ca2790.jpg)

**Comment by filipw** [comment]
Fixed here https://github.com/filipw/AspNetWebApi-OutputCache/pull/95
