### ISSUE TITLE
InvalidateCacheOutput(String, Type) attribute doesn't work

### ISSUE THREAD

**Issue by davecapper** [filipw/AspNetWebApi-OutputCache#58]
The Controller name has "Controller" removed in the attribute constructor, however the CacheOutputAttributes writes to the cache with the Controller still in the name. This means that when it looks for the cache key to invalidate (i.e. WebApiCache.Contains(key)) it doesn't exist.

For example, the key that is created to cache my output is:
"readpositioncontroller-readposition-positionID=2:application/json"

When I try to invalidate the cache using the attribute [InvalidateCacheOutput("ReadPosition", typeof(ReadPositionController))] the key it attempts to find is:
"readposition-readposition", which doesn't exist. 

It looks for this because the constructor for the attribute assigns type.Name.Replace("Controller", string.Empty) to controller instead of just using the type.Name directly. If I remove the .Replace("Controller", string.Empty) it works as expected.

**Comment by cchongchong** [comment]
I got the same issue with Strathweb.CacheOutput.WebApi2 0.9.0
I think this is code issue. 
You can see code in https://github.com/filipw/AspNetWebApi-OutputCache/blob/dev/src/WebApi.OutputCache.V2/DefaultCacheKeyGenerator.cs
The cache key is generated using context.ControllerContext.ControllerDescriptor.ControllerType.FullName which is the full name of controller.
But if you go to https://github.com/filipw/AspNetWebApi-OutputCache/blob/dev/src/WebApi.OutputCache.V2/InvalidateCacheOutputAttribute.cs
The controller name is type.Name.Replace("Controller", string.Empty) which could not be the same as generated cache key.
