### ISSUE TITLE
AllKeys functionality on IApiOutputCache

### ISSUE THREAD

**Issue by alexjamesbrown** [filipw/AspNetWebApi-OutputCache#60]
Would be useful to be able to return an array of keys in the cache

Can do it (on MemoryCacheDefault) like this...

```
return Cache.Select(x=>x.Key);
```

Just wondered if this was viable?

**Comment by johnib** [comment]
I suggest documenting that this is not used by the Core library of `CacheOutput`.
It might be misleading whoever considers implementing the `IApiCacheOutput` interface.

For instance, listing all keys on Redis cache can have huge impact on performance in case of large key set, I almost searched for another distributed cache technology that allows such operation.

**Please document this**
