### ISSUE TITLE
MakeBaseCachekey

### ISSUE THREAD

**Issue by davecapper** [filipw/AspNetWebApi-OutputCache#73]
Hi Filip,

I've run into a problem with the MakeBaseCachekey method because the base cache key is not unique for me. I noticed in "Allow using custom cache keys. #40" that you've discussed how this might be overcome. Do you have any plans to change this, or any recommendations on how this might be changed?

The issue I'm encountering is that I have some entities with the same name but they are in different namespaces. The controller name is the same e.g. ReadServiceCategoryController but they exist in different DLLs or in different namespaces within the same DLL. They even have the same method names because they are automatically generated. MakeBaseCachekey creates the same base key for both of the controllers so they return incorrect information depending on which controller is called first.

I've seen that a new key generator can be plugged in but the MakeBaseCachekey method is still used in some places that can't be replaced. I'd like to fix this in a way that you'd be happy to pull back into the main branch so that I don't get stuck on a fork of your project.

Kind regards,
Dave

**Comment by filipw** [comment]
This has been addressed in #139
