### ISSUE TITLE
HttpResponseMessage not returning on first "cached" request

### ISSUE THREAD

**Issue by erik5388** [filipw/AspNetWebApi-OutputCache#85]
```csharp
[CacheOutput(ClientTimeSpan = 100, ServerTimeSpan = 100)]
public async Task<HttpResponseMessage> Get(string imageId)
{
  if (string.IsNullOrEmpty(imageId))
  {
    return Request.CreateResponse(HttpStatusCode.BadRequest);
  }

  var images = await _repository.Get(imageId);

  if (images == null)
  {
    return Request.CreateResponse(HttpStatusCode.BadRequest);
  }

  if (IsImageRequest)
  {

    if (!File.Exists(images.Path))
    {
      return Request.CreateResponse(HttpStatusCode.Gone);
    }


    HttpResponseMessage response = Request.CreateResponse(HttpStatusCode.OK);
    response.Content = new StreamContent(File.OpenRead(images.Path));
    response.Content.Headers.ContentType = new MediaTypeHeaderValue("image/png");
    response.Headers.Location = new Uri(images.Href);

    return response;

  }

  return Request.CreateResponse(HttpStatusCode.OK, images);
}
```

Model from repository contains path to image on hard disk.

Works fine without cache. Fails to resolve/respond after cache is set.

![capture](https://cloud.githubusercontent.com/assets/183147/3789187/83a43e3a-1a91-11e4-9793-ec5de8744710.PNG)

but when i refresh again, and then subsequently continue refreshing... all is good!

Is this a bug?

![capture_good](https://cloud.githubusercontent.com/assets/183147/3789189/98297442-1a91-11e4-9da1-ed1d0c8010c2.PNG)

**Comment by pleepleus88** [comment]
I was on the verge of ripping out my CacheOutput attributes and using server-side data caching instead, when I found this open issue. I am having the exact same problem - async actions that are cached on the server, deadlocking on only the second request to the endpoint. Did anyone ever find a workaround or solution for this issue?

I wish I had more info to add, but the above comments pretty much cover my findings.

**Comment by dmarlow** [comment]
Same here, I ended up removing CacheOutput on the async API endpoints. It was very hard to track down.

**Comment by sbezludny** [comment]
I encountered a similar problem in my application. Issue was in interaction between OuputCache and Compression Delegating Handler. Thing is that call of ReadAsByteArrayAsync (that is used underhood of OutputCache) caused calculation of content-length after that Compression Delegating Handler used incorrect value of content-length instead to omit that header. Hope this help.

**Comment by erik5388** [comment]
@sbezludny possible pull-request? Help us out brotha!

**Comment by yoyos** [comment]
I'm using the last version https://www.nuget.org/packages/Strathweb.CacheOutput.WebApi2/0.9.0 and still have this deadlock on first request. 

I'using .NET 4.5 Ninject Async actions .. Am I the only one ?

**Comment by pafanasiev** [comment]
Same here, with the latest version of nuget  - this still reproduces for me but only for some controllers?
Has anyone figured out why is this happening?

**Comment by yoyos** [comment]
As I remember, I fixed the problem by disabling all modules in web.config and enabling one by one.
It was coming from another package (a module of https://www.nuget.org/packages/ImageResizer/) that needed an upgrade (pre version) from Sync to Async. You try the same
