### ISSUE TITLE
Caching convention 

### ISSUE THREAD

**Issue by KingR1** [filipw/AspNetWebApi-OutputCache#90]
Hi. Just now i noticed Caching convention : names of methods must be unique.
But i tried it with ununique names : 
`Get() and Get(int id)` , which return different Types

Is browser i firstly ran `Get()` then again. After 2nd run data wasn't modified.
After all i ran `Get(int id)` and data wasn't from cache.

Issue : Caching convention doesn't works or browser lies me?

**Comment by filipw** [comment]
`names of methods must be unique.`

means that `names` not `signatures` must be unique. in your case please use `Get` and `GetById`
